SurfBoard/Models/Outer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurfBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Outer()
        {
            this.OuterOptions = new HashSet<OuterOptions>();
        }
    
        public int Outer_ID { get; set; }
        public int Polls_ID { get; set; }
        public Nullable<int> Outer_Rating { get; set; }
        public string Outer_Text { get; set; }
        public string Outer_Name { get; set; }
        public string OuterSes_ID { get; set; }
    
        public virtual Polls Polls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OuterOptions> OuterOptions { get; set; }
    }
}

SurfBoard/Controllers/OuterController.cs
using SurfBoard.Business;
using SurfBoard.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SurfBoard.Controllers
{
    public class OuterController : Controller
    {
        // GET: Outer
        public ActionResult EnterEvent()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LinkCode(string Code)
        {
            using (ProjectJobEntities db = new ProjectJobEntities())
            {
                var code = Code.ToUpper();
                var eventlist = from ev in db.Event
                                join us in db.Users on ev.Users_ID equals us.User_ID
                                where ev.Event_Code.Contains(code)
                                select new ViewNameEvent
                                {
                                    Event = ev,
                                    Users = us
                                };
                var eventlist2 = eventlist.ToList();
                var list = eventlist2.Select(x => new ViewEventPoll() { LastName = x.Users.LastName, FirstName = x.Users.FirstName, Event_ID = x.Event.Event_ID, Event_Code = x.Event.Event_Code, Event_Name = x.Event.Event_Name, End_Date = x.Event.End_Date, Start_Date = x.Event.Start_Date, Event_Password = x.Event.Event_Password }).OrderByDescending(q => q.Event_ID).ToList();



                return Json(list);
            }

        }
        [HttpPost]
        public ActionResult LinkQuestionPage(int ID)
        {
            using (ProjectJobEntities db = new ProjectJobEntities())

            {
                var model = db.Event.Where(x => x.Event_ID == ID).SingleOrDefault();

                Session["Event_ID"] = ID;

                Session["Event_Code"] = model.Event_Code;

            }
            return Json(new { Url = "QuestionsPage" });

        }

        public ActionResult FindSession()
        {
            var Ses_ID = Convert.ToString(Session["Ses_ID"]);

            if (Ses_ID != "")
            {
                var FindSes_ID = new { CheckSes_ID = "0" };
                return Json(FindSes_ID, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var FindSes_ID = new { CheckSes_ID = "1" };
                return Json(FindSes_ID, JsonRequestBehavior.AllowGet);
            }


        }

        public ActionResult SetSessionOuter(string OuterName)
        {
            var Name = OuterName;

            var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            var random = new Random();
            var NewOuterID = new string(Enumerable.Repeat(chars, 13).Select(s => s[random.Next(s.Length)]).ToArray());

            Session["FirstName"] = Name;
            Session["Ses_ID"] = NewOuterID;

            var React = new { clear = "0" };
            return Json(React, JsonRequestBehavior.AllowGet);

        }
        public ActionResult QuestionsPage()
        {
            var eid = Convert.ToInt32(Session["Event_ID"]);

            using (ProjectJobEntities db = new ProjectJobEntities())
            {
                var findActive = from ev in db.Event
                                 join po in db.Polls on ev.Event_ID equals po.Event_ID
                                 where ev.Event_ID == eid
                                 select new Eventpoll
                                 {
                                     Event = ev,
                                     Poll = po
                                 };
                //var PollActive = findActive.SingleOrDefault(x => x.Poll.IsActive == true);

                //ViewBag.Active = PollActive;
                ViewBag.ThisActive = eid;
               
                return View();


            }
        }
        public JsonResult FindIsActive(int EventID)
        {

            var session = Convert.ToString(Session["Ses_ID"]);

            using (ProjectJobEntities db = new ProjectJobEntities())
            {

                var findActive = from ev in db.Event
                                 join po in db.Polls on ev.Event_ID equals po.Event_ID
                                 where ev.Event_ID == EventID
                                 select new Eventpoll
                                 {
                                     Event = ev,
                                     Poll = po
                                 };

                var numActive = findActive.Where(x => x.Poll.IsActive == true).ToList();
                var CountActive = numActive.Count();
                


                if (CountActive == 1)
                {
                    var PollActive = findActive.FirstOrDefault(x => x.Poll.IsActive == true);
                

                    if (PollActive != null)
                    {

                        var React = new { CheckAct = "1", ID = PollActive.Poll.Polls_ID, Type = PollActive.Poll.Polls_Type_ID };
                        return Json(React, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        var React = new { CheckAct = "0" };
                        return Json(React, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    var React = new { CheckAct = "0" };
                    return Json(React, JsonRequestBehavior.AllowGet);
                }
            }


        }
        public JsonResult FindHasSession()
        {

            var session = Convert.ToString(Session["Ses_ID"]);
            var SessionPollID = Convert.ToInt32(Session["Poll_ID"]);
            using (ProjectJobEntities db = new ProjectJobEntities())
            {

                var HasSession = db.Outer.Where(x => x.OuterSes_ID == session && x.Polls_ID == SessionPollID).Count();

                var PollActive = db.Polls.FirstOrDefault(x => x.Polls_ID == SessionPollID);

                if (HasSession != 0)
                {
                    var React = new { Checksession = "1", ID = PollActive.Polls_ID, Type = PollActive.Polls_Type_ID };
                    return Json(React, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var React = new { Checksession = "2" };
                    return Json(React, JsonRequestBehavior.AllowGet);
                }


            }


        }


        public ActionResult _QRate(int? pid)
        {
            var ID = Convert.ToInt32(Session["Event_ID"]);


            using (ProjectJobEntities db = new ProjectJobEntities())
            {



                var pol = db.Polls.Where(x => x.Polls_ID == pid).SingleOrDefault();
                ViewBag.whatRate = pol;

                var numLimit = pol.LimitPerson;
                var numusercount = db.Outer.Where(x => x.Polls_ID == pid).Count();
                if (numLimit == numusercount)
                {
                    ViewBag.Limitcheck = 1;
                }
                else
                {
                    ViewBag.Limitcheck = 0;
                }

                List<Polls> QRate = new List<Polls>();
                QRate = db.Polls.Where(x => x.Event_ID == ID && x.Polls_ID == pid).ToList();

                
                Session["Poll_ID"] = pid;

                //viewbagdata

                ViewBag.MyQRate = QRate;

                return View();
            }
        }
        public ActionResult _QMulti(int? pid)
        {
            var ID = Convert.ToInt32(Session["Event_ID"]);
            using (ProjectJobEntities db = new ProjectJobEntities())
            {
                List<Polls> QMulti = new List<Polls>();
                QMulti = db.Polls.Where(x => x.Event_ID == ID && x.Polls_ID == pid).ToList();

                //viewbagdata
                ViewBag.MyQMulti = QMulti;
                var Is = db.Polls.Where(x => x.Polls_ID == pid).Select(x => x.IsMulti).ToArray();
                ViewBag.IsMulti = Is;
                var Max = db.Polls.Where(x => x.Polls_ID == pid).Select(x => x.MaxMulti).ToArray();
                ViewBag.MaxLimit = Max;

                var Multi = db.Options.Where(x => x.Polls_ID == pid).ToList();
                ViewBag.MyChoose = Multi;

                var numLimit = QMulti.Select(x => x.LimitPerson).Single();
                var numusercount = db.Outer.Where(x => x.Polls_ID == pid).Count();
                if (numLimit == numusercount)
                {
                    ViewBag.Limitcheck = 1;
                }
                else
                {
                    ViewBag.Limitcheck = 0;
                }

                Session["Poll_ID"] = pid;

                return PartialView();
            }
        }
        public ActionResult _QText(int? pid)
        {
            var ID = Convert.ToInt32(Session["Event_ID"]);
            using (ProjectJobEntities db = new ProjectJobEntities())
            {
                List<Polls> QText = new List<Polls>();
                QText = db.Polls.Where(x => x.Event_ID == ID && x.Polls_ID == pid).ToList();

                var numLimit = QText.Select(x => x.LimitPerson).Single();
                var numusercount = db.Outer.Where(x => x.Polls_ID == pid).Count();
                if (numLimit == numusercount)
                {
                    ViewBag.Limitcheck = 1;
                }
                else
                {
                    ViewBag.Limitcheck = 0;
                }
                //viewbagdata
                ViewBag.MyQText = QText;

                Session["Poll_ID"] = pid;

                return PartialView();
            }
        }
        public ActionResult _QCloud(int? pid)
        {

            var ID = Convert.ToInt32(Session["Event_ID"]);
            using (ProjectJobEntities db = new ProjectJobEntities())
            {
                List<Polls> QCloud = new List<Polls>();

SurfBoard/Views/Outer/EnterEvent.cshtml
@{
    ViewBag.Title = "EnterEvent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <nav class="navbar navbar-fixed-top " style="padding-top:20px;padding-bottom:20px">
        <a class="navbar-brand"></a>

    </nav>


    <div class="container d-inline-block">
        <form class="form-inline form-group" style="padding-left:10px">
            @if (@Session["User_ID"] != null)
            {
                <a href="@Url.Action("BackEvent", "Outer")" class="fa fa-home" style="font-size:40px;color:dimgrey;"> </a>
            }
            @if (@Session["User_ID"] == null)
            {
                <a href="@Url.Action("Back", "Outer")" class="fa fa-home" style="font-size:40px;"></a>
            }




            <label for="Code" style="margin-left:25px">
                <span class="input-group-prepend">
                    <span class="input-group-text bg-light border-light form-control ">
                        <span class="fa fa-hashtag "></span>
                    </span>
                </span>
            </label>
            <input class="form-control text-uppercase" style="border-color:  #92a8d1;" autocomplete="off" id="Code" type="text" placeholder="ค้นหารหัสกิจกรรม" maxlength="4">

            @if (@Session["Ses_ID"] == null)
            {
                <button class="btn example_c" style="margin-left:20px;" onclick="CheckOuter()" type="button">ค้นหา</button>

            }
            @if (@Session["Ses_ID"] != null)
            {
                <button class="btn example_c" style="margin-left:20px;" onclick="CheckNewEnter()" type="button">ค้นหา</button>

            }


        </form>

        <div class="list-group m-2" id="announcement">


        </div>

    </div>

</div>
<div class="modal" id="EnterPassword" tabindex="-1" role="dialog" aria-labelledby="EnterPasswordLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="align-items: center">
            <div class="modal-header  border-0" style="font-weight: normal">

            </div>
            <div class="modal-body" autocomplete="off">
                <input class="form-control " name="EnterPassword2" id="EnterPassword2" placeholder=" กรุณาใส่รหัสผ่านของกิจกรรมนี้" style="width:254px;margin-bottom:-10px;margin-top:-10px" />
            </div>
            <div class="modal-footer border-0">
                <input type="number" id="DeleteEID" hidden />
                <button type="button" class="btn btn-secondary close2" data-dismiss="modal" hidden>Close</button>

                <button type="button" class="btn btn-secondary" style="width:100px" onclick="validatePassword()">ยืนยัน</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="CreateSessionModal" tabindex="-1" role="dialog" aria-labelledby="CreateSessionModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="height:auto;width:400px;align-items:center;">

            <div class="modal-body input-group" autocomplete="off" style="">

                <input class="form-control-plaintext " id="OuterName" placeholder="กรุณาใส่ชื่อของคุณ" />&nbsp;


                <button type="button" class="btn btn-secondary close2" data-dismiss="modal" hidden>Close</button>

                <button type="button" class="btn btn-secondary" style="width:80px;height:auto" onclick="SetOuterSession()">บันทึก</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <link href="~/Style_Sheets/FaFaHover.css" rel="stylesheet" />
    <link href="~/Style_Sheets/EnterStyle.css" rel="stylesheet" />
    <script>
        $('#EnterPassword').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var recipient = button.data('whatever') // Extract info from data-* attributes
            // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
            // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
            var modal = $(this)
            var name = button.data('name')
            modal.find('.modal-header').text('กรุณาใส่รหัสผ่านของกิจกรรม    " ' + name + ' "  ')

            modal.find('.modal-footer input').val(recipient)
        })

    </script>
    @*---Block Input Enter---*@
    <script>
        $(document).ready(function () {
            $(window).keydown(function (event) {
                if (event.keyCode == 13) {
                    event.preventDefault();
                    return false;
                }
            });
        });
    </script>

    <script>
         $(document).ready(function () {


                $.ajax({
                    type: "POST",
                    url: '@Url.Action("FindSession","Outer")',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",

                    success: function (data) {
                        if (data.CheckSes_ID == "1") {
                            $('#CreateSessionModal').modal('show');
                        }
                    },
                    error: function () {
                        console.log("Error Again.")
                    }
                })

         });

        function SetOuterSession() {
                 var OuterName = $("#OuterName").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("SetSessionOuter","Outer")',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: JSON.stringify({ OuterName : OuterName }),
                success: function (data) {
                    location.reload();
                }
            })
        }
        
        function CheckOuter() {
                
            $.ajax({
                type: "POST",
                url: '@Url.Action("FindSession","Outer")',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                
                success: function (data) {
                     if (data.CheckSes_ID == "1") {
                            $('#CreateSessionModal').modal('show');
                        }
                }
            })
        }
    </script>


    <script>
        function CheckNewEnter() {
            var Code = $("#Code").val();
            if (Code == "") {
                return false;
            }
            $.ajax({
                type: "POST",
                url: '@Url.Action("LinkCode","Outer")',
                 ontentType: "application/json; charset=utf-8",
                dataType: "json",
                data: { Code },
                success: function (data) {

                   $('.rows').remove();

                    $.each(data, function (key, val) {
                        var Star =  moment(val.Start_Date).add(543, 'year').add(1,'day').format('DD/MM/YYYY');
                        var End = moment(val.End_Date).add(543, 'year').add(1, 'day').format('DD/MM/YYYY');
                        if (val.Event_Password == null) {
                        var rows = '<div class="list-group rows" style="width:1000px">'
                            + '<div class="card border-gray shadow-sm  w-50  " style="border-color:#92a8d1">'
                            + '<div class="card-body d-flex flex-column align-items-start list-group-item-action" onclick="LinkQuestionPage(' + val.Event_ID + ')" id="' + val.Event_ID + '">'
                            + '<div class="form-inline "  > '
                            + '<h4 style="font-size:medium;color:#92a8d1" class="card-title ">' + val.Event_Name + ' </h4>'
                            + '</div>'
                            + '<div class="form-inline " style="margin-top:-5px;margin-bottom:-5px" > '
                            + '<h6 style="font-size:smaller;color:dimgrey;font-weight: normal;" class="card-title "> ชื่อผู้จัดทำ : </h4>&nbsp;'
                            + '<h6 style="font-size:smaller;color:dimgrey;font-weight: normal;" class="card-title ">' + val.FirstName + ' </h4>&nbsp;'
                            + '<h6 style="font-size:smaller;color:dimgrey;font-weight: normal;" class="card-title ">' + val.LastName+ ' </h4>'
                            + '</div>'
                            + '<p style="font-size:smaller" class="card-text">  ' + Star + '   To   ' + End + ' </p>'
                            + '</div>'
                            + '</div>'
                            + '</div>';
                            }
                       else {
                            var rows = '<div class="list-group rows" style="width:1000px">'
                            + '<div class="card border-gray shadow-sm  w-50  " style="border-color:#92a8d1">'
                            + '<div class="card-body d-flex flex-column align-items-start list-group-item-action" data-toggle="modal" data-target="#EnterPassword" data-whatever="'+val.Event_ID+'" data-Name="'+val.Event_Name+'" >'
                            + '<div class="form-inline "  > '
                            + '<h4 style="font-size:medium;color:#92a8d1" class="card-title ">' + val.Event_Name + ' </h4>'
                            + ' <span class="fa fa-lock pb-2 pl-2" style="font-size:20px;color:gray"></span>'
                            + '</div>'
                            + '<div class="form-inline " style="margin-top:-5px;margin-bottom:-5px" > '
                            + '<h6 style="font-size:smaller;color:dimgrey;font-weight: normal;" class="card-title "> ชื่อผู้จัดทำ : </h4>&nbsp;'
                            + '<h6 style="font-size:smaller;color:dimgrey;font-weight: normal;" class="card-title ">' + val.FirstName + ' </h4>&nbsp;'
                            + '<h6 style="font-size:smaller;color:dimgrey;font-weight: normal;" class="card-title ">' + val.LastName+ ' </h4>'
                            + '</div>'
                            + '<p style="font-size:smaller" class="card-text">  ' + Star + '   To   ' + End + ' </p>'
                            + '</div>'
                            + '</div>'
                            + '</div>';
                        }
                        $('#announcement').append(rows);
                    });
                },
                error: function () {
                    console.log("Error Again.")
                }
            });
        }
    </script>
    <script>
        function LinkQuestionPage(ID) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("LinkQuestionPage","Outer")',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: JSON.stringify({ ID }),
                success: function (result) {
                    window.location.href = result.Url;
                }
            })
        }


    </script>
    <script>
        function validatePassword() {
            var EventID = $("#DeleteEID").val();
            var Password = $("#EnterPassword2").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("validatePassword","Outer")',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: JSON.stringify({ EventID: EventID, Password: Password }),
                success: function (data) {
                     if (data.Pascheck == "") {
                    alert(data.Result);
                    }
                    if (data.Pascheck == "1") {

                        LinkQuestionPage(data.evnet_ID);
                    }
                }
            })
        }


    </script>
}

SurfBoard/Views/Outer/QuestionsPage.cshtml
@{
    ViewBag.Title = "QuestionsPage";
    if (Session["Event_ID"] == null)
    {
        Response.Redirect("~/Home/Index");

    }


    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <nav class="navbar navbar-fixed-top " style="padding-top:20px;padding-bottom:20px">
        <a class="navbar-brand"></a>
    </nav>

    <div>
        <span onclick="window.location.href ='EnterEvent';" style="font-size:35px" class="fa fa-arrow-left"></span>

        <div class="list-group ">

            <div class="card " id="QuestionsBox" style="width:800px;height:auto;align-self:center;border-color:  #92a8d1;">
                <div class="card-body ">

                    <h4 class="card-title text-center p-5" style="color:  #92a8d1">ไม่มีข้อมูลโพลคำถามที่เปิดใช้งาน.<span class="text-uppercase"> @Session["Event_Code"]</span> </h4>


                </div>

            </div>


        </div>

    </div>
</div>
@section scripts{
    <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
    <script src="~/signalr/hubs"></script>

    <link href="~/Style_Sheets/RadioBtn.css" rel="stylesheet" />
    <link href="~/Style_Sheets/ScrollQuestion.css" rel="stylesheet" />
    <link href="~/Style_Sheets/Star.css" rel="stylesheet" />
    <link href="~/Style_Sheets/FaFaHover.css" rel="stylesheet" />
    <link href="~/Style_Sheets/InputTextQ.css" rel="stylesheet" />

    <script>
        $(document).ready(function () {
            $(window).keydown(function (event) {
                if (event.keyCode == 13) {
                    event.preventDefault();
                    return false;
                }
            });
        });
    </script>
    <script>
         $(document).ready(function () {

             var IdsD = @ViewBag.ThisActive;
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("FindIsActive","Outer")',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    data: JSON.stringify({ EventID: IdsD }),
                    success: function (data) {
                        if (data.CheckAct == "1") {
                            var id = data.ID;
                            var type = data.Type;
                            returnQuestionPartial(id, type);

                        }

                    },
                    error: function () {
                        console.log("Error Again.")
                    }
                })

         });

    </script>

    <script>
        function returnQuestionPartial(id, type) {
            var url = "";

            if (type == 1) {
                url = "/Outer/_QMulti"
            }
            if (type == 2) {
                url = "/Outer/_QText"
            }
            if (type == 3) {
                url = "/Outer/_QCloud"
            }
            if (type == 4) {
                url = "/Outer/_QRate"
            }


            $.ajax({
                type: "GET",
                url: url,
                data: {
                    pid: id
                },
                dataType: 'html',
                success: function (data) {
                    $('#QuestionsBox').html(data);
                    CheckHasSessionID()
                },
                error: function () {
                    alert("Hey! Something Eorror.");
                }
            })
        }

        $(function () {

            var hubNotif = $.connection.myHub;

            hubNotif.client.updatedData = function (id, type,checkid) {
                if (checkid == "@Session["Event_ID"]") {
                    returnQuestionPartial(id, type);
                }

            };

            $.connection.hub.start().done(function () {

            });
        })
    </script>
    <script>
         function CheckHasSessionID() {


                $.ajax({
                    type: "POST",
                    url: '@Url.Action("FindHasSession","Outer")',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",

                    success: function (data) {
                        if (data.Checksession == "1") {
                            var id = data.ID;
                            var type = data.Type;
                            SetShowAnswer(id, type);
                        }

                    },
                    error: function () {
                        console.log("Error Again.")
                    }
                })

         };
    </script>
    <script>


        function AddThis() {
            var PId =$("#test").attr("data-id")
            var PType = $("#test").attr("data-bind")
            var text = $("#Text").val();

            var Opt = "";
            $(".option-input:checked").each(function () {
                var a = $(this).attr("data-id");
                var b = a.toString();
                Opt = Opt + " " + b;
            });
            var MaxMulti = $("#check").attr("data-Multi");
            var Rate = $("#star_input").val();

            if (text == undefined) {
                text = null
            }
            if (Rate == undefined) {
                Rate = 0
            }
            if (MaxMulti == undefined) {
                MaxMulti = 10
            }
            if (Opt == "") {
                Opt = 0
            }


            $.ajax({
                    type: "POST",
                    url: '@Url.Action("AddAnswer","Outer")',
                    //contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: { PollTypes: PType, PollID: PId, Text: text, Options: Opt, Rate: Rate ,MaxMulti:MaxMulti},
                success: function (data) {
                    if (data.Check == 1) {
                        alert(data.Result)

                        CallSignalR(data)
                        
                    }
                     if (data.Check == 2) {
                        alert(data.Result)

                         window.location.href = '@Url.Action("EnterEvent", "Outer")';

                    }
                     if (data.Check == 0) {

                    alert(data.Result)
                        }


                    },
                error: function () {
                        alert(" ไม่สามารถส่งคำตอบได้. กรุณารอจนกว่าผู้จัดตั้งจะเปลี่ยนโพลคำตอบ ")
                        console.log("Error Again.")
                    }
                });

        }
        function CallSignalR(data) {
                 $.ajax({
                     type: "GET",
                     url: '@Url.Action("CallSignalR")',
                     data: {
                         id: data.id,
                         type: data.type
                     },
                     success: function () {


                     },
                     error: function () {
                         alert("Hey! Something Eorror.");
                     }
                 })
             }

    </script>
    <script>
        function SetShowAnswer(id, type) {
            var url = "";

            if (type == 1) {
                url = "/Outer/_SetshowMulti"
            }
            if (type == 2) {
                url = "/Outer/_SetshowText"
            }
            if (type == 3) {
                url = "/Outer/_SetshowCloud"
            }
            if (type == 4) {
                url = "/Outer/_SetshowRate"
            }


            $.ajax({
                type: "GET",
                url: url,
                data: {
                    checkid: id
                },
                dataType: 'html',
                success: function (data) {
                    $('#QuestionsBox').html(data);

                },
                error: function () {
                    alert("Hey! Something Eorror.");
                }
            })
        }
    </script>
}